### ISSUE TITLE
Custom properties scoped inside classes throw error

### ISSUE THREAD

**Issue by doctorsirius** [mrmlnc/vscode-csscomb#122]
Having a custom property scoped into a class, like this:

![image](https://user-images.githubusercontent.com/28984901/57572991-419c8e80-7422-11e9-8c6c-9588cf8eb569.png)

Generate the following error on the console:

TypeError: Cannot read property 'first' of null

**Comment by xXGoziXx** [comment]
Apparently it was also an issue in the csscomb package which was then later fixed. So I think it's simply a matter of updating the version of the csscomb package in package.json and installing it.

**Comment by mrmlnc** [comment]
Unfortunately, the new version of CSSComb has no effect for this problem.

```js
const Comb = require('csscomb');

const comb = new Comb('csscomb');

try {
	const res = comb.processPath('./smoke/test.css');

	console.dir(res, { colors: true });
} catch (error) {
	console.dir(error, { colors: true });
}
```

Error:

```js
(node:18460) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'first' of null
    at Plugin._getSortablePropertyName (../vscode-csscomb\node_modules\csscomb\lib\options\sort-order.js:163:44)
    at Plugin._getSortableName (../vscode-csscomb\node_modules\csscomb\lib\options\sort-order.js:158:88)
    at Plugin._extendNode (../vscode-csscomb\node_modules\csscomb\lib\options\sort-order.js:77:29)
    at Plugin._separateSortablesFromBlock (../vscode-csscomb\node_modules\csscomb\lib\options\sort-order.js:341:31)
    at Plugin._processBlock (../vscode-csscomb\node_modules\csscomb\lib\options\sort-order.js:311:28)
    at ../vscode-csscomb\node_modules\gonzales-pe\lib\gonzales.js:312:41
    at Node.traverse (../vscode-csscomb\node_modules\gonzales-pe\lib\gonzales.js:292:6)
    at Node.traverse (../vscode-csscomb\node_modules\gonzales-pe\lib\gonzales.js:297:36)
    at Node.traverse (../vscode-csscomb\node_modules\gonzales-pe\lib\gonzales.js:297:36)
    at Node.traverseByType (../vscode-csscomb\node_modules\gonzales-pe\lib\gonzales.js:311:11)
```

**Comment by mrmlnc** [comment]
This is work if you drop the `sort-order` property:

```
const Comb = require('csscomb');

(async () => {
	try {
		const config = Comb.getConfig('csscomb');

		delete config['sort-order'];

		const comb = new Comb(config);

		const res = await comb.processPath('./smoke/test.css');

		console.dir(res, { colors: true });
	} catch (error) {
		console.dir(error, { colors: true });
	}
})();
```

**Comment by mrmlnc** [comment]
Close as duplicate for https://github.com/mrmlnc/vscode-csscomb/issues/119.
