### ISSUE TITLE
Broken with VSCode 1.15.0

### ISSUE THREAD

**Issue by ArgonAlex** [mrmlnc/vscode-csscomb#82]
```
[CSSComb]

SyntaxError: No one parser could not parse file. See log for more details: []
    at Object.parse (/Users/[user]/.vscode/extensions/mrmlnc.vscode-csscomb-5.1.0/node_modules/config-profiler/out/services/parser.js:43:9)
    at Object.<anonymous> (/Users/[user]/.vscode/extensions/mrmlnc.vscode-csscomb-5.1.0/node_modules/config-profiler/out/services/config.js:37:47)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/[user]/.vscode/extensions/mrmlnc.vscode-csscomb-5.1.0/node_modules/tslib/tslib.js:93:62)
```

**Comment by mrmlnc** [comment]
Most likely this is related to https://code.visualstudio.com/updates/v1_15#_new-api-for-multiroot-workspaces.

**Comment by alexwalter88** [comment]
Ah I have been using npm link to sort of simulate multiple workspaces for a long time, but I'm guessing that some changes to VS Code for real multiple workspaces have some side effects like this.

Anyway, the solution was to simply manually specify the path to the csscomb config file with the `preset` option. That way, when running the extension on CSS files inside of the symlink, it is able to find the config file.

**Comment by mrmlnc** [comment]
I think we need to resolve this issue and not try to live with it.

**Comment by zhaozhe0831** [comment]
I have same problem. 
csscomb can't work in VS 1.15.0 .
```
[CSSComb]

SyntaxError: No one parser could not parse file. See log for more details: []
    at Object.parse (/Users/zhaozhe/.vscode/extensions/mrmlnc.vscode-csscomb-5.1.0/node_modules/config-profiler/out/services/parser.js:43:9)
    at Object.<anonymous> (/Users/zhaozhe/.vscode/extensions/mrmlnc.vscode-csscomb-5.1.0/node_modules/config-profiler/out/services/config.js:37:47)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zhaozhe/.vscode/extensions/mrmlnc.vscode-csscomb-5.1.0/node_modules/tslib/tslib.js:93:62)
```

**Comment by mrmlnc** [comment]
Thanks for report. You also use Multi Workspace? In any case I'll work on this issue today.

**Comment by zhaozhe0831** [comment]
what's the mean of Multi Workspace? double window?
this is my VS.
<img width="1277" alt="2017-08-16 4 41 36" src="https://user-images.githubusercontent.com/12945873/29354955-cb5163b8-82a1-11e7-91f6-5bf54271ca13.png">

**Comment by mrleblanc101** [comment]
@zhaozhe0831 Hi, I know it's not really the place. But what's the UI and Icon theme for VS code ?
