### ISSUE TITLE
Running the contributed command:'csscomb.execute' failed.

### ISSUE THREAD

**Issue by mitchellknight** [mrmlnc/vscode-csscomb#92]
Just switched from Atom to VS Code. Very happy to have found a CSS Comb extension but I'm having some issues.

When I run `CSSComb: Format styles` on my `style.css` file, it gives me an error:

> Running the contributed command:'csscomb.execute' failed.

Here is the configuration in my User Settings:

```json
    "csscomb.preset": {
        "remove-empty-rulesets": true,
        "always-semicolon": true,
        "color-case": "lower",
        "block-indent": "\t",
        "color-shorthand": false,
        "element-case": "lower",
        "eof-newline": true,
        "leading-zero": true,
        "quotes": "single",
        "sort-order-fallback": "abc",
        "space-before-colon": "",
        "space-after-colon": " ",
        "space-before-combinator": " ",
        "space-after-combinator": " ",
        "space-between-declarations": "\n",
        "space-before-opening-brace": " ",
        "space-after-opening-brace": "\n",
        "space-after-selector-delimiter": "\n",
        "space-before-selector-delimiter": "",
        "space-before-closing-brace": "\n",
        "strip-spaces": true,
        "unitless-zero": true
    }
```

I'm running Visual Studio Code 1.16.1 (should be up-to-date) on macOS 10.12.6 Sierra.

Any ideas on how to fix this issue?

Thanks

**Comment by mrmlnc** [comment]
Hello, @mitchellknight,

I trying to format with your config and it's perfectly works. You can provide more information about your workflow (OS, set of extensions and your CSS file (maybe small example))?

**Comment by mitchellknight** [comment]
I'm not sure how much help this is:

- **OS:** macOS 10.12.6 "Sierra"
- **Extensions:** Instead of trying to list them all I disabled them all (except CSSComb), restarted and encountered the same error. That leads me to believe it being related to another extension is unlikely.
- **CSS file:** I'm not sure I can post this (it's for an unreleased work project). I did try CSSComb on multiple other CSS files with the same error. I do not believe it's related to the file itself.

After I run the CSSComb command this shows in the Developer Tools Console:

```console
shell.ts:454 Running the contributed command:'csscomb.execute' failed.: Error: Running the contributed command:'csscomb.execute' failed.
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:348465)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:444633)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290588)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290278)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:289305
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:291224
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:58570
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57853)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:59575)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:107349)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.onUnexpectedError @ shell.ts:454
(anonymous) @ shell.ts:414
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
(anonymous) @ errors.ts:49
(anonymous) @ errors.ts:44
errors.ts:51 WARNING: Promise with no error callback:146
errors.ts:52 Object {exception: null, error: Error: Running the contributed command:'csscomb.execute' failed.
	at e.$executeContributedCommand (/…, promise: n.C…s.d…e._oncancel, handler: undefined, id: 146…}error: Error: Running the contributed command:'csscomb.execute' failed.
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:348465)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:444633)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290588)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290278)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:289305
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:291224
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:58570
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57853)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:59575)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:107349)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)exception: nullhandler: undefinedid: 146parent: undefinedpromise: n.Class.derive._oncancel__proto__: Object
messageService.ts:125 Running the contributed command:'csscomb.execute' failed.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e.resume @ messageService.ts:63
(anonymous) @ workbench.ts:988
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ quickOpenController.ts:534
```

**Comment by taylorbryant** [comment]
I'm having the same issue on two different computers (macOS & Windows 10) after the latest VS Code update.

**Comment by mrmlnc** [comment]
@taylorbryant, you can provide more information about your workflow (OS, set of extensions and your CSS file (maybe small example))?

**Comment by taylorbryant** [comment]
I have a 2016 MacBook Pro that uses macOS High Sierra. I've disabled all other extensions. The only extension active is CSS Comb. 

### My user settings in VS Code (macOS)
```
{
    "workbench.colorTheme": "Dracula",
    "editor.tabSize": 2,
    "editor.wordWrap": "on",
    "files.autoSave": "onFocusChange",
    "html.format.endWithNewline": true,
    "emmet.triggerExpansionOnTab": true,
    "csscomb.formatOnSave": true,
    "window.zoomLevel": 0,
    "workbench.startupEditor": "newUntitledFile",
    "editor.detectIndentation": false,
    "csscomb.preset": "~/.vscode/default.csscomb.json"
}
```

### A simple CSS example
```
body {line-height: 1.5;}
```

Just to add: I tried using the extension without a preset defined, and I experienced the same issues.

**Comment by taylorbryant** [comment]
### Here's the error log from the Developer Tools
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 Running the contributed command:'csscomb.execute' failed.: Error: Running the contributed command:'csscomb.execute' failed.
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:348465)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:444633)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290588)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290278)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:289305
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:291224
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:58570
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57853)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:59575)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:107349)
e.onUnexpectedError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 WARNING: Promise with no error callback:91
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 Object
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 Running the contributed command:'csscomb.execute' failed.
```

**Comment by mrmlnc** [comment]
Very strange. I tried to reproduce this problem on macOS Sierra (10.12.6) with VS Code 1.17.0 and Today Insiders and I do not see the error.

You can create GIF/Video for your case? Maybe you can debug plugin? For debugging:

  0. `git clone https://github.com/mrmlnc/vscode-csscomb`
  1. `cd vscode-csscomb`
  2. `npm i`
  3. `npm run build`
  4. `code .`
  5. Press <kbd>F5<\kbd>
  6. In the new window run CSSComb command

**Comment by mitchellknight** [comment]
`extension.js:38`:

```javascript
        const workspace = workspaceFolder.uri.fsPath;
```

Shows this:

```error

Exception has occurred: TypeError
TypeError: Cannot read property 'uri' of undefined
	at vscode.commands.registerTextEditorCommand (/Users/octaneagency/Desktop/test/vscode-csscomb/out/extension.js:38:42)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:425319
	at t.e.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:328898)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:425285
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:348393)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:444633)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290588)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:290278)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:289305
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:291224

```

I'm not much of a JavaScript programmer (and I'm new to VS Code) so I'm not sure if there are any other errors. I just noticed that message when I followed your instructions to debug the plugin.

**Comment by mrmlnc** [comment]
Should works fine after 5.2.1. Thanks to @mrSauceman (https://github.com/mrmlnc/vscode-postcss-sorting/issues/76#issuecomment-336917842)
